apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url:   "manifest repository url"
  password: "GitHub fined grained token to access this repository"
  username: not-used