apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc-claim
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cluster-persistent-storage
  resources:
    requests:
      storage: 1Gi