kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cluster-persistent-storage
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: "Your EFS file sytem Id"
  directoryPerms: "700"